### ISSUE TITLE
[Request] New DFC Symbols

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#102]
New symbols (front/back indicators and Meld indicator) for dual face cards.

**Front**
![front icon](https://user-images.githubusercontent.com/4212200/224572825-63a3bdab-8249-4822-b5a0-b1dc9a006d32.png)

**Back**
![back_icon](https://user-images.githubusercontent.com/4212200/224572834-b332a07a-b9c5-4dd9-a942-98d6604d7ca8.png)

**Meld**
![meld icon](https://user-images.githubusercontent.com/4212200/224576724-2614e114-67a4-4529-a9dd-17cb7207ff35.png)

**Comment by RivalRowan** [comment]
Just further to [4eveRS](https://github.com/4eveRS)'s point, WotC has updated the Comprehensive Rules as of The Brothers' War so that these three symbols are now the standard indicator symbols for all double-faced cards and Meld cards.

**712.1a** A transforming double-faced card’s front face is marked by a front-face symbol in its upper left corner. On cards printed starting with The Brothers’ War™ release, that symbol is a single white triangle pointed upward inside a black circle.

**712.1b** A transforming double-faced card’s back face is marked by a back-face symbol in its upper left corner. On cards printed starting with The Brothers’ War release, that symbol is a single white triangle pointed downward inside a black circle.

Meld card icons don't have a rules definition in the CR but the recent reprints of meld cards from Shadows over Innistrad Remastered on MTG Arena used The Brothers' War icon rather than their original icons.

**Comment by andrewgioia** [comment]
Added in 1.15.6
