### ISSUE TITLE
Kamigawa Neon Saga Transform

### ISSUE THREAD

**Issue by MrTeferi** [andrewgioia/mana#88]
Title says it all, we need the NEO saga transform symbol :)

**Comment by gbartholomeu** [comment]
I'm working on a minimalist proxy maker. While creating minimalist phyrexian hybrid mana I created a new font containing the new Saga icon: https://github.com/gbartholomeu/mtg-minimalist-proxies/blob/master/minimalistproxies/html/css/mana.css 

.ms-kamigawa-saga

Since I created the vector from scratch, it isn't 100% like Wizard's original art but it ended very close to it. 

OR, if you want, just download the .xcf I created (https://github.com/gbartholomeu/mtg-minimalist-proxies-support/blob/main/kamigawa.xcf), convert to Vector/Path and create the icon using IcoMoon as andrewgioia guides in his README.md. Feel free to adjust to your needs.
